// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AulaCoreDesktop.Data
{
    public partial class Cliente
    {
        [Key]
        [Column("Cli_ID")]
        public int CliId { get; set; }
        [Required]
        [Column("Cli_Nome")]
        [StringLength(50)]
        public string CliNome { get; set; }
        [Required]
        [Column("Cli_Email")]
        [StringLength(50)]
        public string CliEmail { get; set; }
        [Required]
        [Column("Cli_CPF")]
        [StringLength(50)]
        public string CliCpf { get; set; }
    }
}