// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AulaCoreDesktop.Data
{
    public partial class Fornecedor
    {
        [Key]
        [Column("For_ID")]
        public int ForId { get; set; }
        [Required]
        [Column("For_Nome")]
        [StringLength(50)]
        public string ForNome { get; set; }
    }
}